#!/bin/bash
# Configure X11 to render on a 3.5" SPI TFT (ILI9486) via /dev/fb0.
#
# What this does:
#   1. Installs xserver-xorg-video-fbdev (X11 framebuffer driver)
#   2. Creates /etc/X11/xorg.conf.d/99-spi-tft.conf  — forces X to use fb0
#   3. Comments out phantom-HDMI lines in /boot/firmware/config.txt
#   4. Creates touch calibration for rotated display
#   5. Installs hud.service for auto-start on boot
#
# LightDM stays on Wayland (labwc) so RPi Connect keeps working.
# start.sh detects the SPI display at runtime and starts X on fb0 itself.
#
# Run on the Pi as:  sudo bash scripts/setup-spi-display.sh
# Reboot after:      sudo reboot
# Undo later with:   sudo bash scripts/teardown-spi-display.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: Run with sudo" >&2
    exit 1
fi

HUD_USER="${SUDO_USER:-pi}"
HUD_HOME="/home/$HUD_USER"
CONFIG_TXT="/boot/firmware/config.txt"
XORG_CONF_DIR="/etc/X11/xorg.conf.d"
XORG_CONF="$XORG_CONF_DIR/99-spi-tft.conf"
echo "=== SPI TFT Display Setup ==="

# ---- 1. Verify fb0 exists ----
if [ ! -e /dev/fb0 ]; then
    echo "ERROR: /dev/fb0 not found. Is the SPI overlay loaded?" >&2
    echo "Check: dtoverlay=piscreen in $CONFIG_TXT and dtparam=spi=on" >&2
    exit 1
fi
echo "[OK] /dev/fb0 exists"

# ---- 2. Install fbdev X11 driver ----
if dpkg -s xserver-xorg-video-fbdev &>/dev/null; then
    echo "[OK] xserver-xorg-video-fbdev already installed"
else
    echo "Installing xserver-xorg-video-fbdev..."
    apt-get update -qq
    apt-get install -y xserver-xorg-video-fbdev
fi

# ---- 3. Create X11 config — force fbdev on /dev/fb0 ----
mkdir -p "$XORG_CONF_DIR"
cat > "$XORG_CONF" << 'XORGEOF'
# Auto-generated by setup-spi-display.sh — render X11 on SPI TFT (fb0)
# Remove this file (or run teardown-spi-display.sh) to go back to HDMI.

Section "Device"
    Identifier "SPITFT"
    Driver     "fbdev"
    Option     "fbdev" "/dev/fb0"
EndSection

Section "Monitor"
    Identifier "SPIMonitor"
EndSection

Section "Screen"
    Identifier  "SPIScreen"
    Device      "SPITFT"
    Monitor     "SPIMonitor"
    DefaultDepth 16
    SubSection "Display"
        Depth  16
        Modes  "480x320"
    EndSubSection
    SubSection "Display"
        Depth  24
        Modes  "480x320"
    EndSubSection
EndSection

Section "ServerLayout"
    Identifier "Layout0"
    Screen     "SPIScreen"
EndSection
XORGEOF
echo "[OK] Created $XORG_CONF"

# ---- 4. Patch config.txt — comment out phantom HDMI lines ----
if [ -f "$CONFIG_TXT" ]; then
    BACKUP="$CONFIG_TXT.before-spi.bak"
    if [ ! -f "$BACKUP" ]; then
        cp "$CONFIG_TXT" "$BACKUP"
        echo "[OK] Backed up $CONFIG_TXT → $BACKUP"
    fi

    sed -i \
        -e 's/^hdmi_force_hotplug=1/# [spi-setup] hdmi_force_hotplug=1/' \
        -e 's/^hdmi_group=2/# [spi-setup] hdmi_group=2/' \
        -e 's/^hdmi_mode=87/# [spi-setup] hdmi_mode=87/' \
        -e 's/^hdmi_cvt=/#  [spi-setup] hdmi_cvt=/' \
        "$CONFIG_TXT"
    echo "[OK] Commented out phantom-HDMI lines in $CONFIG_TXT"
else
    echo "WARN: $CONFIG_TXT not found — skip patching"
fi

# ---- 5. Touch calibration (Y-axis inversion for rotate=270) ----
TOUCH_CONF="$XORG_CONF_DIR/99-touch-calibration.conf"
cat > "$TOUCH_CONF" << 'TOUCHEOF'
Section "InputClass"
    Identifier "SPI Touchscreen"
    MatchProduct "ADS7846"
    Option "TransformationMatrix" "1 0 0 0 -1 1 0 0 1"
EndSection
TOUCHEOF
echo "[OK] Created $TOUCH_CONF (Y-axis fix for rotate=270)"

# ---- 6. Grant pi user access to fb0 (udev rule) ----
UDEV_RULE="/etc/udev/rules.d/99-fbdev.rules"
if [ ! -f "$UDEV_RULE" ]; then
    echo 'SUBSYSTEM=="graphics", KERNEL=="fb0", MODE="0666"' > "$UDEV_RULE"
    echo "[OK] Created $UDEV_RULE (world-readable fb0)"
fi

# ---- 7. Install hud.service ----
echo "Installing hud.service..."
SERVICE_FILE="$PROJECT_DIR/systemd/hud.service"
if [ -f "$SERVICE_FILE" ]; then
    sed -e "s|/home/pi/car-hud-pi|$PROJECT_DIR|g" \
        -e "s|User=pi|User=$HUD_USER|g" \
        -e "s|/home/pi|$HUD_HOME|g" \
        "$SERVICE_FILE" | tee /etc/systemd/system/hud.service > /dev/null
    systemctl daemon-reload
    systemctl enable hud.service
    echo "[OK] Installed and enabled hud.service"
else
    echo "WARN: $SERVICE_FILE not found — skip service install"
fi

# ---- 8. Make scripts executable ----
chmod +x "$PROJECT_DIR/scripts/"*.sh 2>/dev/null || true
echo "[OK] Scripts marked executable"

echo ""
echo "=== Done ==="
echo "Reboot now:  sudo reboot"
echo ""
echo "After reboot the HUD will auto-start on the 3.5\" SPI display."
echo "To undo (switch back to HDMI):  sudo bash scripts/teardown-spi-display.sh"
